spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/issue
    username: wave
    password: 0913
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

auth:
  url: http://localhost:9090/api/v1/users/me
